import moment from "moment";

export const TASK_TAGS = [
    {
        name: "Event",
        color: "#FF7800",
        id: "event",
        lightColor: "#FFD5A0",
        lighterColor: "#fff1e5",
    },
    {
        name: "Meeting",
        color: "#33A8FF",
        id: "meeting",
        lightColor: "#B3E0FF",
        lighterColor: "#eaf6ff",
    },
    {
        name: "Important",
        color: "#FF0000",
        id: "important",
        lightColor: "#FFB3B3",
        lighterColor: "#ffe5e5",
    },
];

export const formatTime = (time) => {
    if (!time) return "";
    if (time instanceof Date) {
        return moment(time).format("HH:mm");
    }
    return time;
};

export const sortUpcomingTaskByDate = (tasks) => {
    const today = moment().startOf('day');
    return [...tasks]
        .filter((task) => !task.isCompleted && moment(task.date).isSameOrAfter(today))
        .sort((a, b) => {
            const dateA = new Date(`${a.date}T${a.start}`);
            const dateB = new Date(`${b.date}T${b.start}`);
            return dateA - dateB;
        });
};

export const TEST_DATA = [
    {
        id: "task-1",
        title: "Go to the gym",
        description: "I would like to do a full body workout",
        date: "2026-02-08",
        start: "07:00",
        end: "08:30",
        tag: {
            name: "Event",
            color: "#FF7800",
            id: "event",
            lightColor: "#FFD5A0",
            lighterColor: "#fff1e5",
        },
        isCompleted: false,
    },
    {
        id: "task-2",
        title: "Team standup",
        description: "Daily sync with the dev team",
        date: "2026-02-08",
        start: "09:00",
        end: "09:30",
        tag: {
            name: "Meeting",
            color: "#33A8FF",
            id: "meeting",
            lightColor: "#B3E0FF",
            lighterColor: "#eaf6ff",
        },
        isCompleted: true,
    },
    {
        id: "task-3",
        title: "Submit tax documents",
        description: "Deadline for quarterly tax filing",
        date: "2026-02-10",
        start: "10:00",
        end: "11:00",
        tag: {
            name: "Important",
            color: "#FF0000",
            id: "important",
            lightColor: "#FFB3B3",
            lighterColor: "#ffe5e5",
        },
        isCompleted: false,
    },
    {
        id: "task-4",
        title: "Dentist appointment",
        description: "Regular checkup and cleaning",
        date: "2026-02-09",
        start: "14:00",
        end: "15:00",
        tag: {
            name: "Event",
            color: "#FF7800",
            id: "event",
            lightColor: "#FFD5A0",
            lighterColor: "#fff1e5",
        },
        isCompleted: false,
    },
    {
        id: "task-5",
        title: "Client presentation",
        description: "Present Q1 roadmap to stakeholders",
        date: "2026-02-11",
        start: "11:00",
        end: "12:30",
        tag: {
            name: "Meeting",
            color: "#33A8FF",
            id: "meeting",
            lightColor: "#B3E0FF",
            lighterColor: "#eaf6ff",
        },
        isCompleted: false,
    },
    {
        id: "task-6",
        title: "Pay rent",
        description: "Monthly rent payment due",
        date: "2026-02-01",
        start: "09:00",
        end: "09:15",
        tag: {
            name: "Important",
            color: "#FF0000",
            id: "important",
            lightColor: "#FFB3B3",
            lighterColor: "#ffe5e5",
        },
        isCompleted: true,
    },
    {
        id: "task-7",
        title: "Birthday party",
        description: "Sarah's surprise birthday party",
        date: "2026-02-14",
        start: "18:00",
        end: "22:00",
        tag: {
            name: "Event",
            color: "#FF7800",
            id: "event",
            lightColor: "#FFD5A0",
            lighterColor: "#fff1e5",
        },
        isCompleted: false,
    },
    {
        id: "task-8",
        title: "1:1 with manager",
        description: "Weekly check-in and career discussion",
        date: "2026-02-12",
        start: "15:00",
        end: "15:30",
        tag: {
            name: "Meeting",
            color: "#33A8FF",
            id: "meeting",
            lightColor: "#B3E0FF",
            lighterColor: "#eaf6ff",
        },
        isCompleted: false,
    },
    {
        id: "task-9",
        title: "Renew passport",
        description: "Passport expires next month",
        date: "2026-02-15",
        start: "10:00",
        end: "12:00",
        tag: {
            name: "Important",
            color: "#FF0000",
            id: "important",
            lightColor: "#FFB3B3",
            lighterColor: "#ffe5e5",
        },
        isCompleted: false,
    },
    {
        id: "task-10",
        title: "Yoga class",
        description: "Hot yoga session at the studio",
        date: "2026-02-08",
        start: "17:30",
        end: "18:30",
        tag: {
            name: "Event",
            color: "#FF7800",
            id: "event",
            lightColor: "#FFD5A0",
            lighterColor: "#fff1e5",
        },
        isCompleted: false,
    },
    {
        id: "task-11",
        title: "Sprint planning",
        description: "Plan tasks for the next two weeks",
        date: "2026-02-10",
        start: "10:00",
        end: "11:30",
        tag: {
            name: "Meeting",
            color: "#33A8FF",
            id: "meeting",
            lightColor: "#B3E0FF",
            lighterColor: "#eaf6ff",
        },
        isCompleted: false,
    },
    {
        id: "task-12",
        title: "Doctor follow-up",
        description: "Review blood test results",
        date: "2026-02-13",
        start: "09:00",
        end: "09:30",
        tag: {
            name: "Important",
            color: "#FF0000",
            id: "important",
            lightColor: "#FFB3B3",
            lighterColor: "#ffe5e5",
        },
        isCompleted: false,
    },
    {
        id: "task-13",
        title: "Concert night",
        description: "Live band at the downtown venue",
        date: "2026-02-20",
        start: "20:00",
        end: "23:00",
        tag: {
            name: "Event",
            color: "#FF7800",
            id: "event",
            lightColor: "#FFD5A0",
            lighterColor: "#fff1e5",
        },
        isCompleted: false,
    },
    {
        id: "task-14",
        title: "Design review",
        description: "Review new UI mockups with design team",
        date: "2026-02-09",
        start: "14:00",
        end: "15:00",
        tag: {
            name: "Meeting",
            color: "#33A8FF",
            id: "meeting",
            lightColor: "#B3E0FF",
            lighterColor: "#eaf6ff",
        },
        isCompleted: true,
    },
    {
        id: "task-15",
        title: "Car insurance renewal",
        description: "Policy expires this week",
        date: "2026-02-08",
        start: "12:00",
        end: "12:30",
        tag: {
            name: "Important",
            color: "#FF0000",
            id: "important",
            lightColor: "#FFB3B3",
            lighterColor: "#ffe5e5",
        },
        isCompleted: false,
    },
    {
        id: "task-16",
        title: "Hiking trip",
        description: "Trail hike with friends",
        date: "2026-02-22",
        start: "08:00",
        end: "14:00",
        tag: {
            name: "Event",
            color: "#FF7800",
            id: "event",
            lightColor: "#FFD5A0",
            lighterColor: "#fff1e5",
        },
        isCompleted: false,
    },
    {
        id: "task-17",
        title: "Board meeting",
        description: "Quarterly board review",
        date: "2026-02-18",
        start: "13:00",
        end: "15:00",
        tag: {
            name: "Meeting",
            color: "#33A8FF",
            id: "meeting",
            lightColor: "#B3E0FF",
            lighterColor: "#eaf6ff",
        },
        isCompleted: false,
    },
    {
        id: "task-18",
        title: "Submit project proposal",
        description: "Final deadline for grant application",
        date: "2026-02-16",
        start: "17:00",
        end: "17:30",
        tag: {
            name: "Important",
            color: "#FF0000",
            id: "important",
            lightColor: "#FFB3B3",
            lighterColor: "#ffe5e5",
        },
        isCompleted: false,
    },
    {
        id: "task-19",
        title: "Cooking class",
        description: "Learn to make Italian pasta",
        date: "2026-02-21",
        start: "18:00",
        end: "20:00",
        tag: {
            name: "Event",
            color: "#FF7800",
            id: "event",
            lightColor: "#FFD5A0",
            lighterColor: "#fff1e5",
        },
        isCompleted: false,
    },
    {
        id: "task-20",
        title: "Interview candidate",
        description: "Technical interview for senior dev role",
        date: "2026-02-11",
        start: "16:00",
        end: "17:00",
        tag: {
            name: "Meeting",
            color: "#33A8FF",
            id: "meeting",
            lightColor: "#B3E0FF",
            lighterColor: "#eaf6ff",
        },
        isCompleted: false,
    },
];
